### ISSUE TITLE
Hii bro , I just have a small doubt regarding this radio player package on the app that I am working, on can u please clarify it ?

### ISSUE THREAD

**Issue by ampro88** [DemeoStep/MyRadio#1]

**Comment by DemeoStep** [comment]
What the trouble?

**Comment by ampro88** [comment]
The issue is am getting a default notification on top using this radio player package with only play button . I also want to have next and previous buttons ,
 how to dot that ? this is also preventing me to use custom notifications , so am stuck :(( plzzz help bro

**Comment by DemeoStep** [comment]
Use this package for player https://pub.dev/packages/flutter_radio_player
Or use this with radio_player package for notifications https://pub.dev/packages/audio_service

**Comment by ampro88** [comment]
Can we integrate audio_service with radio player package ? how would I disable the deafault notification created by this radio plater package ?

**Comment by ampro88** [comment]
I need to disable think existing notification to use the other

**Comment by DemeoStep** [comment]
Dig into package and modify it if you can not use other

**Comment by ampro88** [comment]
I do not know how to do that man thats the issue , do u have discord ? I can share my screen and code , can u just help me to spot that ? Its just minutes of work , can u please help bro ?

**Comment by DemeoStep** [comment]
Just use other package

**Comment by ampro88** [comment]
I mean its a long process, u cant spare some time bro?

**Comment by DemeoStep** [comment]
It would be better to you to do it yourself

**Comment by ampro88** [comment]
Am just stuck , bro maybe can u help me to spot the part of code which causes this automatic notification from radio player package ?
